from .dictionary import (
    DictionaryEntry,
    WorkDictionary,
    apply_dictionary,
    ensure_dictionary_storage,
    load_work_dictionary,
    save_work_dictionary,
    sync_work_dictionary,
)
from .diarization import DiarizationError, DiarizationSegment, diarize_wav
from .persistence import (
    PersistenceError,
    ensure_voiceprint_storage,
    export_episode_csv,
    export_episode_txt,
    load_library_state,
    load_voiceprint_state,
    save_library_state,
    save_voiceprint_state,
)
from .preprocess import MediaPreprocessError, PreprocessResult, extract_audio_clip, preprocess_media
from .speaker_id import (
    SpeakerIdentificationError,
    VoiceprintAssignment,
    VoiceprintMatch,
    assign_voiceprints_to_segments,
    average_embedding,
    build_voiceprint_sample,
    cosine_similarity,
    extract_voice_embedding,
    score_voiceprint_profiles,
    select_best_voiceprint_match,
    upsert_voiceprint_profile,
)
from .transcription import (
    DEFAULT_MODEL_NAME,
    MODEL_OPTIONS,
    TranscriptionError,
    TranscriptionSegment,
    normalize_model_selection,
    transcribe_wav,
)

__all__ = [
    "DictionaryEntry",
    "DiarizationError",
    "DiarizationSegment",
    "MediaPreprocessError",
    "PersistenceError",
    "PreprocessResult",
    "DEFAULT_MODEL_NAME",
    "MODEL_OPTIONS",
    "SpeakerIdentificationError",
    "TranscriptionError",
    "TranscriptionSegment",
    "VoiceprintAssignment",
    "VoiceprintMatch",
    "WorkDictionary",
    "apply_dictionary",
    "assign_voiceprints_to_segments",
    "average_embedding",
    "build_voiceprint_sample",
    "cosine_similarity",
    "diarize_wav",
    "ensure_dictionary_storage",
    "ensure_voiceprint_storage",
    "extract_audio_clip",
    "export_episode_csv",
    "export_episode_txt",
    "extract_voice_embedding",
    "load_library_state",
    "load_voiceprint_state",
    "load_work_dictionary",
    "normalize_model_selection",
    "preprocess_media",
    "save_library_state",
    "save_voiceprint_state",
    "save_work_dictionary",
    "score_voiceprint_profiles",
    "select_best_voiceprint_match",
    "sync_work_dictionary",
    "transcribe_wav",
    "upsert_voiceprint_profile",
]
